AllCops:
  TargetRubyVersion: 2.7

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
  
Layout/LineLength:
  Max: 120
